analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - unnecessary_new
    - unnecessary_const
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - unawaited_futures
